<?php
    Route::get('icons' , 'HomeController@icons');
    Route::get('docs' , 'HomeController@apiDocs');
    #### user control
    Route::get('user' , 'UserController@index');
    Route::get('user/item/{id?}' , 'UserController@show');
    Route::post('user/item/{id?}' , 'UserController@store');
    Route::get('user/{id}/delete' , 'UserController@destroy');
    Route::get('user/{id}/view' , 'UserController@getById');
    #### group control
    Route::get('group' , 'GroupController@index');
    Route::get('group/item/{id?}' , 'GroupController@show');
    Route::post('group/item/{id?}' , 'GroupController@store');
    Route::get('group/{id}/delete' , 'GroupController@destroy');
    Route::get('group/{id}/view' , 'GroupController@getById');
    #### role control
    Route::get('role' , 'RoleController@index');
    Route::get('role/item/{id?}' , 'RoleController@show');
    Route::post('role/item/{id?}' , 'RoleController@store');
    Route::get('role/{id}/delete' , 'RoleController@destroy');
    Route::get('role/{id}/view' , 'RoleController@getById');
    #### permission control
    Route::get('permission' , 'PermissionController@index');
    Route::get('permission/item/{id?}' , 'PermissionController@show');
    Route::post('permission/item/{id?}' , 'PermissionController@store');
    Route::get('permission/{id}/delete' , 'PermissionController@destroy');
    Route::get('permission/{id}/view' , 'PermissionController@getById');
    #### home control
    Route::get('home/{pages?}/{limit?}' , 'HomeController@index');
    #### setting control
    Route::get('setting' , 'SettingController@index');
    Route::get('setting/item/{id?}' , 'SettingController@show');
    Route::post('setting/item/{id?}' , 'SettingController@store');
    Route::get('setting/{id}/delete' , 'SettingController@destroy');
    Route::get('setting/{id}/view' , 'SettingController@getById');
    #### menu control
    Route::get('menu' , 'MenuController@index');
    Route::get('menu/item/{id?}' , 'MenuController@show');
    Route::post('menu/item/{id?}' , 'MenuController@store');
    Route::get('menu/{id}/delete' , 'MenuController@destroy');
    Route::get('menu/{id}/view' , 'MenuController@getById');
    Route::post('update/menuItem' , 'MenuController@menuItem');
    Route::post('addNewItemToMenu' , 'MenuController@addNewItemToMenu');
    Route::get('deleteMenuItem/{id}' , 'MenuController@deleteMenuItem');
    Route::get('getItemInfo/{id}' , 'MenuController@getItemInfo');
    Route::post('updateOneMenuItem' , 'MenuController@updateOneMenuItem');


    #### page control
    Route::get('page' , 'PageController@index');
    Route::get('page/item/{id?}' , 'PageController@show');
    Route::post('page/item/{id?}' , 'PageController@store');
    Route::get('page/{id}/delete' , 'PageController@destroy');
    Route::get('page/{id}/view' , 'PageController@getById');
    #### log control
    Route::get('log' , 'LogController@index');
    Route::get('log/item/{id?}' , 'LogController@show');
    Route::post('log/item/{id?}' , 'LogController@store');
    Route::get('log/{id}/delete' , 'LogController@destroy');
    Route::get('log/{id}/view' , 'LogController@getById');
    #### categorie control
    Route::get('categorie' , 'CategorieController@index');
    Route::get('categorie/item/{id?}' , 'CategorieController@show');
    Route::post('categorie/item/{id?}' , 'CategorieController@store');
    Route::get('categorie/{id}/delete' , 'CategorieController@destroy');
    Route::get('categorie/{id}/view' , 'CategorieController@getById');

    #### country control
    Route::get('country' , 'CountryController@index');
    Route::get('country/item/{id?}' , 'CountryController@show');
    Route::post('country/item/{id?}' , 'CountryController@store');
    Route::get('country/{id}/delete' , 'CountryController@destroy');
    Route::get('country/{id}/view' , 'CountryController@getById');
    #### state control
    Route::get('state' , 'StateController@index');
    Route::get('state/item/{id?}' , 'StateController@show');
    Route::post('state/item/{id?}' , 'StateController@store');
    Route::get('state/{id}/delete' , 'StateController@destroy');
    Route::get('state/{id}/view' , 'StateController@getById');
    #### product control
    Route::get('product' , 'ProductController@index');
    Route::get('product/item/{id?}' , 'ProductController@show');
    Route::post('product/item/{id?}' , 'ProductController@store');
    Route::get('product/{id}/delete' , 'ProductController@destroy');
    Route::get('product/{id}/view' , 'ProductController@getById');


    Route::get('getUser' , 'ProductController@getUser');
    Route::get('getState/{id}' , 'ProductController@getState');







    #### contact control
    Route::get('contact' , 'ContactController@index');
    Route::get('contact/item/{id?}' , 'ContactController@show');
    Route::post('contact/item/{id?}' , 'ContactController@store');
    Route::get('contact/{id}/delete' , 'ContactController@destroy');
    Route::get('contact/{id}/view' , 'ContactController@getById');
    #### branch control
    Route::get('branch' , 'BranchController@index');
    Route::get('branch/item/{id?}' , 'BranchController@show');
    Route::post('branch/item/{id?}' , 'BranchController@store');
    Route::get('branch/{id}/delete' , 'BranchController@destroy');
    Route::get('branch/{id}/view' , 'BranchController@getById');
    #### section control
    Route::get('section' , 'SectionController@index');
    Route::get('section/item/{id?}' , 'SectionController@show');
    Route::post('section/item/{id?}' , 'SectionController@store');
    Route::get('section/{id}/delete' , 'SectionController@destroy');
    Route::get('section/{id}/view' , 'SectionController@getById');
    #### level control
    Route::get('level' , 'LevelController@index');
    Route::get('level/item/{id?}' , 'LevelController@show');
    Route::post('level/item/{id?}' , 'LevelController@store');
    Route::get('level/{id}/delete' , 'LevelController@destroy');
    Route::get('level/{id}/view' , 'LevelController@getById');
    #### shoab control
    Route::get('shoab' , 'ShoabController@index');
    Route::get('shoab/item/{id?}' , 'ShoabController@show');
    Route::post('shoab/item/{id?}' , 'ShoabController@store');
    Route::get('shoab/{id}/delete' , 'ShoabController@destroy');
    Route::get('shoab/{id}/view' , 'ShoabController@getById');
    #### student_group control
    Route::get('student_group' , 'Student_groupController@index');
    Route::get('student_group/item/{id?}' , 'Student_groupController@show');
    Route::post('student_group/item/{id?}' , 'Student_groupController@store');
    Route::get('student_group/{id}/delete' , 'Student_groupController@destroy');
    Route::get('student_group/{id}/view' , 'Student_groupController@getById');
    #### course control
    Route::get('course' , 'CourseController@index');
    Route::get('course/item/{id?}' , 'CourseController@show');
    Route::post('course/item/{id?}' , 'CourseController@store');
    Route::get('course/{id}/delete' , 'CourseController@destroy');
    Route::get('course/{id}/view' , 'CourseController@getById');
    #### level_course control
    Route::get('level_course' , 'Level_courseController@index');
    Route::get('level_course/item/{id?}' , 'Level_courseController@show');
    Route::post('level_course/item/{id?}' , 'Level_courseController@store');
    Route::get('level_course/{id}/delete' , 'Level_courseController@destroy');
    Route::get('level_course/{id}/view' , 'Level_courseController@getById');
    #### student control
    Route::get('student' , 'StudentController@index');
    Route::get('student/item/{id?}' , 'StudentController@show');
    Route::post('student/item/{id?}' , 'StudentController@store');
    Route::get('student/{id}/delete' , 'StudentController@destroy');
    Route::get('student/{id}/view' , 'StudentController@getById');
    #### degreepart control
    Route::get('degreepart' , 'DegreepartController@index');
    Route::get('degreepart/item/{id?}' , 'DegreepartController@show');
    Route::post('degreepart/item/{id?}' , 'DegreepartController@store');
    Route::get('degreepart/{id}/delete' , 'DegreepartController@destroy');
    Route::get('degreepart/{id}/view' , 'DegreepartController@getById');
    #### grade control
    Route::get('grade' , 'GradeController@index');
    Route::get('grade/item/{id?}' , 'GradeController@show');
    Route::post('grade/item/{id?}' , 'GradeController@store');
    Route::get('grade/{id}/delete' , 'GradeController@destroy');
    Route::get('grade/{id}/view' , 'GradeController@getById');
    #### terms control
    Route::get('terms' , 'TermsController@index');
    Route::get('terms/item/{id?}' , 'TermsController@show');
    Route::post('terms/item/{id?}' , 'TermsController@store');
    Route::get('terms/{id}/delete' , 'TermsController@destroy');
    Route::get('terms/{id}/view' , 'TermsController@getById');
    #### control control
    Route::get('control' , 'ControlController@index');
    Route::get('control/item/{id?}' , 'ControlController@show');
    Route::post('control/item/{id?}' , 'ControlController@store');
    Route::get('control/{id}/delete' , 'ControlController@destroy');
    Route::get('control/{id}/view' , 'ControlController@getById');
    #### legan control
    Route::get('legan' , 'LeganController@index');
    Route::get('legan/item/{id?}' , 'LeganController@show');
    Route::post('legan/item/{id?}' , 'LeganController@store');
    Route::get('legan/{id}/delete' , 'LeganController@destroy');
    Route::get('legan/{id}/view' , 'LeganController@getById');
    #### degree control
    Route::get('degree' , 'DegreeController@index');
    Route::get('degree/item/{id?}' , 'DegreeController@show');
    Route::post('degree/item/{id?}' , 'DegreeController@store');
    Route::get('degree/{id}/delete' , 'DegreeController@destroy');
    Route::get('degree/{id}/view' , 'DegreeController@getById');
    #### area control
    Route::get('area' , 'AreaController@index');
    Route::get('area/item/{id?}' , 'AreaController@show');
    Route::post('area/item/{id?}' , 'AreaController@store');
    Route::get('area/{id}/delete' , 'AreaController@destroy');
    Route::get('area/{id}/view' , 'AreaController@getById');
    #### bus control
    Route::get('bus' , 'BusController@index');
    Route::get('bus/item/{id?}' , 'BusController@show');
    Route::post('bus/item/{id?}' , 'BusController@store');
    Route::get('bus/{id}/delete' , 'BusController@destroy');
    Route::get('bus/{id}/view' , 'BusController@getById');
    #### archive control
    Route::get('archive' , 'ArchiveController@index');
    Route::get('archive/item/{id?}' , 'ArchiveController@show');
    Route::post('archive/item/{id?}' , 'ArchiveController@store');
    Route::get('archive/{id}/delete' , 'ArchiveController@destroy');
    Route::get('archive/{id}/view' , 'ArchiveController@getById');
    #### archiveitem control
    Route::get('archiveitem' , 'ArchiveitemController@index');
    Route::get('archiveitem/item/{id?}' , 'ArchiveitemController@show');
    Route::post('archiveitem/item/{id?}' , 'ArchiveitemController@store');
    Route::get('archiveitem/{id}/delete' , 'ArchiveitemController@destroy');
    Route::get('archiveitem/{id}/view' , 'ArchiveitemController@getById');
    #### studentparent control
    Route::get('studentparent' , 'StudentparentController@index');
    Route::get('studentparent/item/{id?}' , 'StudentparentController@show');
    Route::post('studentparent/item/{id?}' , 'StudentparentController@store');
    Route::get('studentparent/{id}/delete' , 'StudentparentController@destroy');
    Route::get('studentparent/{id}/view' , 'StudentparentController@getById');